services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service-container
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]  #-f option to return the status in the case having error
      interval: 10s
      retries: 4

  config-service:
    build: ./config-service
    container_name: config-service-container
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka
  customer-service:
    build: ./customer-service
    container_name: customer-service-container
    ports:
      - '8080:8080'
    expose:
      - '8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      - CONFIG_SERVICE_URL=http://config-service-container:9999
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka

  account-service:
    build: ./account-service
    container_name: account-service-container
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      customer-service:
        condition: service_healthy
    environment:
      - CONFIG_SERVICE_URL=http://config-service-container:9999
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service-container
    ports:
      - '8888:8888'
    expose:
      - '8888'
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/refresh"]
    depends_on:
      account-service:
        condition: service_healthy
    environment:
      - CONFIG_SERVICE_URL=http://config-service-container:9999
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka
