services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service-container
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]  #-f option to return the status in the case having error
      interval: 10s

  config-service:
    build: ./config-service
    container_name: config-service-container
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
    depends_on:
      discovery-service:
        condition: service_healthy
#  customer-service:
#    build: ./customer-service
#    container_name: customer-service-container
#    ports:
#      - '8080:8080'
#    expose:
#      - '8080'
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/actiuator/health"]
#
#  account-service:
#    build: ./account-service
#    container_name: account-service-container
#    ports:
#      - '8081:8081'
#    expose:
#      - '8081'
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/refresh"]
#
#  gateway-service:
#    build: ./gateway-service
#    container_name: gateway-service-container
#    ports:
#      - '8888:8888'
#    expose:
#      - '8888'
#    healthcheck:
#      test: ["CMD", "curl", "-f", "htpp://localhost:8888/actuator/refresh"]
